# Generated by Django 5.1.6 on 2025-02-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_menu.fullmainmenu'),
            preserve_default=False,
        ),
    ]
