# Generated by Django 5.1.6 on 2025-02-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_menu', '0002_extras_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras',
            name='name',
        ),
        migrations.AddField(
            model_name='fullmainmenu',
            name='extras_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_menu.extras'),
            preserve_default=False,
        ),
    ]
