# Generated by Django 5.1.6 on 2025-02-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_menu', '0004_bestsellers_drinks_mainmenu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainMenu',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bestsellers',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bestsellers',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bestsellers',
            name='title_en',
            field=models.CharField(max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='bestsellers',
            name='title_ru',
            field=models.CharField(max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='drinks',
            name='drinks_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drinks_menu', to='test_menu.fullmainmenu'),
        ),
        migrations.AddField(
            model_name='extras',
            name='extras_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras_menu', to='test_menu.fullmainmenu'),
        ),
        migrations.AddField(
            model_name='extras',
            name='title_en',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='extras',
            name='title_ru',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='fullmainmenu',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_menu', to='test_menu.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fullmainmenu',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fullmainmenu',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fullmainmenu',
            name='title_en',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='fullmainmenu',
            name='title_ru',
            field=models.CharField(max_length=233, null=True),
        ),
    ]
