# Generated by Django 5.1.6 on 2025-02-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_menu', '0005_delete_mainmenu_aboutus_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='title_en',
            field=models.CharField(max_length=233, null=True),
        ),
        migrations.AddField(
            model_name='drinks',
            name='title_ru',
            field=models.CharField(max_length=233, null=True),
        ),
    ]
